// templates/solid-ssr/src/client.tsx
import { hydrate } from 'solid-js/web';
import App from './app.js';
import router from './router.js';

import './app.css';
import { acceptInteractions } from '@airlib/solid/browser';

router
  .activate(window.location.href)
  .then(() => {
    hydrate(() => <App />, document.getElementById('root')!);
  })
  .then(() => acceptInteractions());

// apps/air-web/src/client.tsx
import '@airlib/react/client';

import { hydrateRoot } from 'react-dom/client';
import App from './app.js';
import router from './router.js';

import './app.css';
import { acceptInteractions } from '@airlib/react/browser';

router
  .activate(window.location.href)
  .then(() => {
    hydrateRoot(document.getElementById('root')!, <App />);
  })
  .then(() => acceptInteractions());
