// apps/vue/src/components/todo/TodoStats.vue
<script setup lang="ts">
  import type { ITodoList } from './types.js';
  import { ref, type Ref } from 'vue';
  import { derivedRef } from '@anchor/vue';
  import { flashNode } from '../../lib/node.js';

  const { todos } = defineProps<{ todos: ITodoList | Ref<ITodoList> }>();
  const stats = derivedRef(todos, (todos) => {
    return {
      total: todos.length,
      active: todos.filter((todo) => !todo.completed).length,
      completed: todos.filter((todo) => todo.completed).length,
    };
  });

  const statsRef = ref(null);
  flashNode(statsRef);
</script>

<template>
  <div
    ref="statsRef"
    class="todo-stats mt-4 flex justify-between items-center bg-white rounded-lg border border-slate-200 p-4">
    <div class="todo-stats-item flex flex-col items-center">
      <span class="todo-stats-label text-sm text-gray-500">Total</span>
      <span class="todo-stats-value text-lg font-semibold">{{ stats.total }}</span>
    </div>
    <div class="todo-stats-item flex flex-col items-center">
      <span class="todo-stats-label text-sm text-gray-500">Active</span>
      <span class="todo-stats-value text-lg font-semibold text-blue-600">{{ stats.active }}</span>
    </div>
    <div class="todo-stats-item flex flex-col items-center">
      <span class="todo-stats-label text-sm text-gray-500">Completed</span>
      <span class="todo-stats-value text-lg font-semibold text-green-600">{{ stats.completed }}</span>
    </div>
  </div>
</template>

// apps/react/src/components/todo/TodoStats.tsx
import { type FC, useRef } from 'react';
import type { ITodoStats } from '@lib/todo.js';
import { useObserved } from '@anchor/react';
import { flashNode } from '@lib/stats.js';

export const TodoStats: FC<{ stats: ITodoStats }> = ({ stats }) => {
  const ref = useRef(null);
  const [total, active, completed] = useObserved(() => [stats.total, stats.active, stats.completed], [stats]);

  flashNode(ref.current);

  return (
    <div ref={ref} className="flex items-center justify-between px-10 pb-4">
      <div className="flex flex-col items-center">
        <span className="text-lg font-semibold text-slate-400">{total}</span>
        <span className="text-xs text-gray-500">Total</span>
      </div>
      <div className="flex flex-col items-center">
        <span className="text-lg font-semibold text-blue-600">{active}</span>
        <span className="text-xs text-gray-500">Active</span>
      </div>
      <div className="flex flex-col items-center">
        <span className="text-lg font-semibold text-green-600">{completed}</span>
        <span className="text-xs text-gray-500">Completed</span>
      </div>
    </div>
  );
};
