// templates/react-ssr/src/client.tsx
import '@anchorlib/react/client'; // MUST be first import

import { hydrateRoot } from 'react-dom/client';
import App from './app.js';
import router from './router.js';

import './app.css';
import { acceptInteractions } from '@anchorlib/react/browser';

router
  .activate(window.location.href)
  .then(() => {
    hydrateRoot(document.getElementById('root')!, <App />);
  })
  .then(() => acceptInteractions());

// templates/air-solid/src/client.tsx
import { hydrate } from 'solid-js/web';
import App from './app.js';
import router from './router.js';

import './app.css';
import { acceptInteractions } from '@anchorlib/solid/browser';

router
  .activate(window.location.href)
  .then(() => {
    hydrate(() => <App />, document.getElementById('root')!);
  })
  .then(() => acceptInteractions());
