// apps/svelte/src/lib/components/todo/TodoList.svelte
<script lang="ts">
	import TodoStats from './TodoStats.svelte';
	import TodoItem from '$lib/components/todo/TodoItem.svelte';
	import type { TodoRecList } from '../../todos.js';

	const { todos }: { todos: TodoRecList } = $props();
	const items = $derived(todos.filter((todo) => !todo.deleted_at));
</script>

<ul
	class="todo-list divide-y divide-gray-200 rounded-lg bg-gray-50 dark:divide-slate-600 dark:bg-slate-700"
>
	{#each items as todo (todo.id)}
		<TodoItem {todo} />
	{:else}
		<li class="p-4 text-center text-gray-500 dark:text-slate-400">
			No tasks yet. Add a new task to get started!
		</li>
	{/each}
</ul>

<TodoStats {todos} />

// apps/solid/src/components/TodoList.tsx
import { derived } from '@anchorlib/solid';
import { For } from 'solid-js';
import type { TodoRecList } from '../utils/todos.js';
import TodoItem from './TodoItem.js';
import TodoStats from './TodoStats.js';

interface TodoListProps {
  todos: TodoRecList;
}

export default function TodoList({ todos }: TodoListProps) {
  const items = derived(() => todos.filter((todo) => !todo.deleted_at));

  return (
    <>
      <ul class="todo-list divide-y divide-gray-200 rounded-lg bg-gray-50 dark:divide-slate-600 dark:bg-slate-700">
        {items.value.length > 0 ? (
          <For each={items.value}>{(todo) => <TodoItem todo={todo} />}</For>
        ) : (
          <li class="p-4 text-center text-gray-500 dark:text-slate-400">
            No tasks yet. Add a new task to get started!
          </li>
        )}
      </ul>

      <TodoStats todos={todos} />
    </>
  );
}
