// templates/air-react/src/components/InputField.tsx
import { render, setup, type Bindable } from '@anchorlib/react';

type FieldError = { message: string } | undefined;

export const InputField = setup<{
  id: string;
  type?: string;
  label: string;
  value?: Bindable<string>;
  error?: FieldError;
}>((props) => {
  return render(() => (
    <div className="field">
      <label htmlFor={props.id}>{props.label}</label>
      <input id={props.id} type={props.type ?? 'text'} className="field-input" value={props.value} onChange={(e) => { props.value = e.currentTarget.value; }} />
      {props.error ? <span className="field-error">{props.error.message}</span> : null}
    </div>
  ));
}, 'InputField');

export default InputField;

// templates/air-solid/src/components/InputField.tsx
import { type Bindable, setup } from '@anchorlib/solid';
import type { JSX } from 'solid-js';

type FieldError = { message: string } | undefined;

export const InputField = setup<{
  id: string;
  type?: string;
  label: string;
  value?: Bindable<string>;
  error?: FieldError;
}>((props) => {
  const handleInput: JSX.InputEventHandlerUnion<HTMLInputElement, InputEvent> = (e) => {
    props.value = e.currentTarget.value;
  };

  return (
    <div class="field">
      <label for={props.id}>{props.label}</label>
      <input id={props.id} type={props.type ?? 'text'} class="field-input" value={props.value} onInput={handleInput} />
      {props.error ? <span class="field-error">{props.error.message}</span> : null}
    </div>
  );
});

export default InputField;
