// demos/vue/src/components/todo/TodoForm.vue
<script setup lang="ts">
  import { ref } from 'vue';
  import { flashNode } from '../../lib/node.js';
  import { type TodoRecList, todoTable } from '../../lib/todos.js';
  import Plus from '../icons/Plus.vue';

  const newText = ref('');
  const { todos } = defineProps<{ todos: TodoRecList }>();

  const handleAdd = () => {
    if (newText.value.trim() !== '') {
      const todo = todoTable.add({ text: newText.value, completed: false });
      todos.push(todo.data);
      newText.value = '';
    }
  };

  const formRef = ref(null);
  flashNode(formRef);
</script>

<template>
  <div ref="formRef" class="todo-form mb-6">
    <div class="flex gap-2">
      <input
        type="text"
        placeholder="Add a new task..."
        v-model="newText"
        @keyup.enter="handleAdd"
        class="flex-1 px-4 py-2 border border-gray-300 dark:border-slate-600 dark:bg-slate-700 dark:text-white rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
      <button
        @click="handleAdd"
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg transition duration-200">
        <Plus />
      </button>
    </div>
  </div>
</template>

// apps/svelte/src/lib/components/todo/TodoForm.svelte
<script lang="ts">
	import Plus from '../icons/Plus.svelte';
	import { flashNode } from '../../node.svelte.js';
	import { type TodoRecList, todoTable } from '../../todos.js';
	import type { KeyboardEventHandler } from 'svelte/elements';
	import { anchorRef } from '@anchorlib/svelte';

	let newText = $state('');

	const { todos }: { todos: TodoRecList } = $props();

	const handleAdd = () => {
		if (newText.trim() !== '') {
			const todo = todoTable.add({ text: newText, completed: false });
			todos.push(todo.data);
			newText = '';
		}
	};

	const handleEnter: KeyboardEventHandler<HTMLInputElement> = (e) => {
		if (e.key !== 'Enter') return;
		handleAdd();
	};

	let formRef = anchorRef<HTMLElement | null>(null);
	flashNode(formRef);
</script>

<div bind:this={$formRef} class="todo-form mb-6">
	<div class="flex gap-2">
		<input
			type="text"
			placeholder="Add a new task..."
			bind:value={newText}
			onkeyup={handleEnter}
			class="flex-1 rounded-lg border border-gray-300 px-4 py-2 focus:border-transparent focus:ring-2 focus:ring-blue-500 focus:outline-none dark:border-slate-600 dark:bg-slate-700 dark:text-white"
		/>
		<button
			onclick={handleAdd}
			class="rounded-lg bg-blue-500 px-4 py-2 font-bold text-white transition duration-200 hover:bg-blue-700"
		>
			<Plus />
		</button>
	</div>
</div>
