// ui/solid-form/src/inputs/TextInput.tsx
import type { Bindable } from '@airlib/solid';
import type { JSX } from 'solid-js';
import { createInput } from './createInput.js';

export interface TextInputProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<string>;
}
export const TextInput = createInput<TextInputProps>('text');

// ui-kits/react-form/src/inputs/TextInput.tsx
import type { FormInput } from '@airlib/form';
import type { Bindable } from '@airlib/react';
import type { ComponentProps, ReactNode } from 'react';
import { createInput } from './createInput.js';

export interface TextInputProps extends Omit<ComponentProps<'input'>, 'value' | 'children'> {
  for?: TextInputProps;
  errorClass?: string;
  value?: Bindable<string>;
  children?: ReactNode | ((props: ComponentProps<'input'>, input: FormInput<string>) => ReactNode);
}
export const TextInput = createInput<TextInputProps>('text');
