// packages/solid/src/image.tsx
import { type JSX, splitProps } from 'solid-js';

export interface AirImageMeta {
  src: string;
  width: number;
  height: number;
  alt: string;
}

export interface AirImage extends AirImageMeta {
  srcset: string;
  sizes: Record<number, AirImageMeta>;
  default: AirImageMeta;
  [size: number]: AirImageMeta;
}

export interface ImageProps extends JSX.ImgHTMLAttributes<HTMLImageElement> {
  from?: AirImage;
  size?: number;
}

export function Image(props: ImageProps): JSX.Element {
  const [local, imgProps] = splitProps(props, ['from', 'size', 'src', 'width', 'height', 'alt', 'srcset']);

  const target = () => {
    const from = local.from;
    if (!from) return null;
    return local.size !== undefined && from[local.size] ? from[local.size] : from;
  };

  return (
    <img
      src={local.src ?? target()?.src}
      width={local.width ?? target()?.width}
      height={local.height ?? target()?.height}
      alt={local.alt ?? target()?.alt}
      srcset={local.srcset ?? (target() && 'srcset' in target()! ? (target() as AirImage).srcset : undefined)}
      {...imgProps}
    />
  );
}

// packages/react/src/image.tsx
import type { ImgHTMLAttributes, ReactNode } from 'react';
import { snippet } from './hoc.js';

export interface AirImageMeta {
  src: string;
  width: number;
  height: number;
  alt: string;
}

export interface AirImage extends AirImageMeta {
  srcset: string;
  sizes: Record<number, AirImageMeta>;
  [size: number]: AirImageMeta;
}

export interface ImageProps extends ImgHTMLAttributes<HTMLImageElement> {
  from: AirImage;
  size?: number;
}

export type ImageNode = (props: ImageProps) => ReactNode;

export const Image = snippet<ImageProps>(
  ({ from = {} as AirImage, size, src, width, height, alt, srcSet, ...props }) => {
    const target = size !== undefined && from[size] ? from[size] : from;

    return (
      <img
        src={src ?? target.src}
        width={width ?? target.width}
        height={height ?? target.height}
        alt={alt ?? target.alt}
        srcSet={srcSet ?? ('srcset' in target ? (target as AirImage).srcset : undefined)}
        {...props}
      />
    );
  },
  'Image',
  'Slot',
  false
) as ImageNode;
