// packages/solid/src/ref.ts
import { anchor } from '@anchorlib/core';
import { onCleanup } from 'solid-js';
import { REF_REGISTRY } from './reactive.js';
import type { ConstantRef, VariableRef } from './types.js';

/**
 * @deprecated Use 'mutable()' instead.
 * Creates a reactive variable reference that can be used in Solid components.
 * This function creates a reactive state container that integrates with Solid's reactivity system
 * and Anchor's state management. The returned reference object provides getter and setter access
 * to the underlying reactive value.
 *
 * @typeParam T - The type of the value being stored
 * @param init - The initial value for the reactive variable
 * @returns A VariableRef object with getter and setter for the reactive value
 */
export function variableRef<T>(init: T): VariableRef<T>;

/**
 * @deprecated Use 'mutable()' instead.
 * Creates a constant reactive reference that can be used in Solid components.
 * This overload creates a read-only reactive reference that integrates with Solid's reactivity system.
 * The returned reference object only provides a getter for the underlying reactive value.
 *
 * @typeParam T - The type of the value being stored
 * @param init - The initial value for the reactive variable
 * @param constant - A literal true value to indicate this should be a constant reference
 * @returns A ConstantRef object with only a getter for the reactive value
 */
export function variableRef<T>(init: T, constant: true): ConstantRef<T>;

/**
 * @deprecated Use 'mutable()' instead.
 * Creates a reactive reference that can be used in Solid components.
 * This function creates a reactive state container that integrates with Solid's reactivity system
 * and Anchor's state management. Depending on the constant parameter, it returns either a
 * mutable reference (with getter and setter) or an immutable reference (with only getter).
 *
 * @typeParam T - The type of the value being stored
 * @param init - The initial value for the reactive variable
 * @param constant - Optional flag to indicate if this should be a constant (read-only) reference
 * @returns Either a VariableRef (if constant is false/undefined) or ConstantRef (if constant is true)
 */
export function variableRef<T>(init: T, constant?: boolean): VariableRef<T> {
  const state = anchor({ value: init }, { recursive: true });
  const stateRef =
    constant === true
      ? {
          get value() {
            return state.value;
          },
        }
      : {
          get value() {
            return state.value;
          },
          set value(value: T) {
            state.value = value;
          },
        };

  REF_REGISTRY.add(stateRef);

  onCleanup(() => {
    anchor.destroy(state);
    REF_REGISTRY.delete(stateRef);
  });

  return stateRef;
}

/**
 * @deprecated Use 'immutable()' instead.
 * Creates a constant reactive reference that can be used in Solid components.
 * This is a convenience function that creates a read-only reactive reference by calling
 * variableRef with the constant flag set to true.
 *
 * @typeParam T - The type of the value being stored
 * @param init - The initial value for the reactive variable
 * @returns A ConstantRef object with only a getter for the reactive value
 */
export function constantRef<T>(init: T): ConstantRef<T> {
  return variableRef(init, true);
}

/**
 * @deprecated Use 'isValueRef()' instead.
 * Checks if a given value is a reactive reference created by variableRef or constantRef.
 * This function can be used to determine if an object is a reactive reference that
 * integrates with the Solid and Anchor reactivity systems.
 *
 * @param state - The value to check
 * @returns true if the value is a reactive reference, false otherwise
 */
export function isRef(state: unknown): state is VariableRef<unknown> | ConstantRef<unknown> {
  return REF_REGISTRY.has(state as VariableRef<unknown>);
}

// packages/react/src/ref.ts
import { useCallback, useEffect, useRef, useState } from 'react';
import { anchor, captureStack, softClone, softEqual } from '@anchorlib/core';
import { useMicrotask } from './hooks.js';
import type { ConstantRef, RefInitializer, RefUpdater, StateRef, VariableRef } from './types.js';
import { CLEANUP_DEBOUNCE_TIME } from './constant.js';

const REF_REGISTRY = new WeakMap();

export function useVariable<T>(init: T): [VariableRef<T>, RefUpdater<T>];
export function useVariable<T>(init: T, constant: true): [ConstantRef<T>];
export function useVariable<T>(init: RefInitializer<T>, deps: unknown[]): [VariableRef<T>, RefUpdater<T>];
export function useVariable<T>(init: RefInitializer<T>, deps: unknown[], constant: true): [ConstantRef<T>];
export function useVariable<T>(
  init: T | RefInitializer<T>,
  constantDeps?: boolean | unknown[],
  constant?: boolean
): [VariableRef<T>, RefUpdater<T>] | [ConstantRef<T>] {
  if (constantDeps === true) constant = constantDeps;

  const [cleanup, cancelCleanup] = useMicrotask(CLEANUP_DEBOUNCE_TIME);
  const [state] = useState<StateRef<T>>(() => {
    return anchor({
      value: typeof init === 'function' ? (init as RefInitializer<T>)() : init,
    });
  });

  const update = useCallback((value: T) => {
    if (initRef.constant === true) {
      captureStack.violation.general(
        'Assignment violation detected:',
        'Attempted to modify the value of a constant.',
        new Error('Constant is read-only'),
        [
          'Constant value cannot be changed after created.',
          '- Constant only updated when its dependency changed.',
          '- Use variable if you need to update its value later.',
        ],
        Object.getOwnPropertyDescriptors(stateRef).value.set
      );
      return;
    }

    if (value === state.value) return;

    state.value = value;
  }, []);

  const initRef = useRef({
    init,
    deps: [] as unknown[],
    stable: false,
    constant,
  }).current;

  if (typeof init === 'function' && Array.isArray(constantDeps) && !initRef.deps.length) {
    initRef.deps = softClone(constantDeps);
  }

  const stateRef = useRef({
    get value() {
      return state.value;
    },
    set value(value: T) {
      update(value);
    },
  }).current;

  if (initRef.stable) {
    if (typeof initRef.init === 'function') {
      const newDeps = getNextDeps(initRef.deps, softClone(Array.isArray(constantDeps) ? constantDeps : []));

      if (newDeps) {
        state.value = (init as RefInitializer<T>)(state.value);
        initRef.deps = newDeps;
      }
    } else {
      if (initRef.constant !== constant) {
        initRef.constant = constant;
      }

      if (initRef.init !== init) {
        state.value = init as T;
        initRef.init = init;
      }
    }
  } else {
    initRef.stable = true;
  }

  REF_REGISTRY.set(stateRef, state);

  useEffect(() => {
    cancelCleanup();

    return () => {
      cleanup(() => {
        anchor.destroy(state);
        REF_REGISTRY.delete(stateRef);
      });
    };
  }, []);

  if (constant === true) {
    return [stateRef];
  }

  return [stateRef, update];
}

/**
 * Creates a constant reference that never changes its value.
 *
 * @template T - The type of the constant value
 * @param init - The initial value or initializer function
 * @returns A tuple containing the constant reference
 */
export function useConstant<T>(init: T): [ConstantRef<T>];

/**
 * Creates a constant reference that only updates when dependencies change.
 *
 * @template T - The type of the constant value
 * @param init - The initializer function that computes the constant value
 * @param deps - Dependency array that determines when the constant should be recalculated
 * @returns A tuple containing the constant reference
 */
export function useConstant<T>(init: RefInitializer<T>, deps: unknown[]): [ConstantRef<T>];

/**
 * Implementation of useConstant that creates a constant reference.
 *
 * @template T - The type of the constant value
 * @param init - The initial value or initializer function
 * @param deps - Optional dependency array for computed constants
 * @returns A tuple containing the constant reference
 */
export function useConstant<T>(init: T | RefInitializer<T>, deps?: unknown[]): [ConstantRef<T>] {
  return useVariable(init as RefInitializer<T>, deps as unknown[], true);
}

/**
 * Determines whether an update is needed by comparing previous and next dependency arrays.
 *
 * @param prev - The previous dependency array
 * @param next - The next dependency array
 * @returns The next array if an update is needed, otherwise undefined
 */
export function getNextDeps(prev: unknown[], next: unknown[]): unknown[] | undefined {
  if (prev.length !== next.length) return next;
  for (let i = 0; i < prev.length; i++) {
    if (!softEqual(prev[i], next[i], true)) return next;
  }
}

/**
 * Checks if a value is a reference (either variable or constant).
 *
 * @param value - The value to check
 * @returns True if the value is a reference, false otherwise
 */
export function isRef(value: unknown): value is VariableRef<unknown> | ConstantRef<unknown> {
  return REF_REGISTRY.has(value as WeakKey);
}
