// packages/solid/src/switch.ts
import type { AnyType } from '@airlib/core';
import { createMemo, type JSX, untrack } from 'solid-js';

export type ShowProps<T> = {
  when: T;
  children: JSX.Element | ((value: NonNullable<T>) => JSX.Element);
  fallback?: JSX.Element;
};

/**
 * Conditionally renders children based on a truthy condition.
 * Passes the unwrapped truthy value to the children render prop.
 *
 * @param props.when - The condition to evaluate.
 * @param props.children - The content to render when the condition is truthy.
 * @param props.fallback - Optional content to render when the condition is falsy.
 * @returns The rendered content or null.
 */
export function Show<T>(props: ShowProps<T>): JSX.Element {
  const condition = createMemo(() => props.when);

  return createMemo(() => {
    const value = condition();
    if (value) {
      const child = props.children;
      const isRenderProp = typeof child === 'function' && child.length > 0;

      return isRenderProp ? untrack(() => (child as any)(value as NonNullable<T>)) : child;
    }
    return props.fallback;
  }) as unknown as JSX.Element;
}

export type SnippetProxy<T extends Record<string | symbol, AnyType>> = {
  [K in keyof T]: T[K] extends object ? () => T[K] : T[K];
};
export type SnippetProps<T extends Record<string | symbol, AnyType>> = {
  data?: T;
  children: (data: SnippetProxy<T>) => JSX.Element;
};

/**
 * A snippet renderer component that allows for dynamic data rendering and destructure access
 * without losing the fine-grained reactivity.
 *
 * Each property of the data object is proxied to a function that returns the corresponding value.
 *
 * @param props.data - The data to render.
 * @param props.children - The render function that takes the data and returns a JSX element.
 * @returns A JSX element.
 */
export function Snippet<T extends Record<string | symbol, AnyType>>(props: SnippetProps<T>) {
  const dataProxy = new Proxy(props.data ?? ({} as T), {
    get(target, prop) {
      return () => (target as object)[prop as never];
    },
  });

  return props.children(dataProxy as T);
}

export type SlotProps = {
  for: JSX.Element | (() => JSX.Element);
  children?: JSX.Element | (() => JSX.Element);
};

/**
 * Renders content based on a slot function or expression.
 *
 * @param props.for - The slot content or function to render.
 * @param props.children - Optional content to render if no slot content is provided.
 * @returns The rendered content from the slot function or children.
 */
export function Slot(props: SlotProps): JSX.Element {
  const content = createMemo(() => (typeof props.for === 'function' ? (props.for as () => JSX.Element)() : props.for));

  return createMemo(() => {
    const value = content();
    if (value !== undefined && value !== null) {
      return value;
    }
    const fallback = props.children;
    return typeof fallback === 'function' ? (fallback as () => JSX.Element)() : fallback;
  }) as unknown as JSX.Element;
}

// packages/react/src/switch.tsx
import { getContext, setContext } from '@airlib/core';
import type { ReactNode } from 'react';
import { render, setup, snippet } from './hoc.js';

export type SwitchSlotProps<K> = {
  for: K;
  children?: ReactNode | (() => ReactNode);
};

export type SwitchSlotNode<K> = (props: SwitchSlotProps<K>) => ReactNode;

export type SwitchProps<T> = {
  for: T;
  children?: ReactNode;
};

export type SwitchNode<T, K> = ((props: SwitchProps<T>) => ReactNode) & {
  displayName: string;
  Slot: SwitchSlotNode<K>;
};

/**
 * Creates a Slot component that conditionally renders its children based on a context value.
 *
 * @param ctx - The context key to retrieve the state from.
 * @param key - The property key within the state to compare against.
 * @param displayName - Optional display name for the component.
 * @returns A Slot component.
 */
export function createSlot<K>(ctx: string | symbol, key: string | symbol, displayName = 'Anonymous') {
  return snippet<SwitchSlotProps<string>>(
    (props) => {
      const state = getContext(ctx) as Record<string, unknown>;
      if (!state) return '<>[Slot Error: Slot rendered outside of Switch]</>';
      const children = typeof props.children === 'function' ? props.children() : props.children;
      return state[key as string] === props.for ? children : null;
    },
    displayName,
    'SwitchSlot',
    false
  ) as SwitchSlotNode<K>;
}

/**
 * Creates a Switch component and an associated Slot component for conditional rendering.
 *
 * @param ctx - The context key to store the switch state.
 * @param key - The property key within the state that Slots will check.
 * @param displayName - Optional display name for the Switch component.
 * @param scopeName - Optional scope name for the display name (defaults to 'Switch').
 * @returns A Switch component with a static Slot property.
 */
export function createSwitch<T, K>(
  ctx: string | symbol,
  key: string | symbol,
  displayName = 'Anonymous',
  scopeName = 'Switch'
) {
  const Switch = setup((props) => {
    setContext(ctx, (props as never as SwitchProps<T>).for);
    return render(() => (props as never as SwitchProps<T>).children);
  }, displayName) as unknown as SwitchNode<T, K>;

  Switch.displayName = `${scopeName}(${displayName})`;
  Switch.Slot = createSlot<K>(ctx, key, displayName);

  return Switch as SwitchNode<T, K>;
}

export type ShowProps<T> = {
  when: T | (() => T);
  children: ReactNode | ((value: T) => ReactNode);
  fallback?: () => ReactNode;
};

export type ShowNode = <T>(props: ShowProps<T>) => ReactNode;

/**
 * Conditionally renders children based on a truthy condition.
 *
 * @param props.when - The condition to evaluate.
 * @param props.children - The content to render when the condition is truthy.
 * @param props.fallback - Optional content to render when the condition is falsy.
 * @returns The rendered content or null.
 */
export const Show = snippet<ShowProps<boolean>>(
  (props) => {
    const check = typeof props.when === 'function' ? props.when : () => props.when;
    const value = check() as boolean;

    if (value) {
      return typeof props.children === 'function' ? props.children(value) : props.children;
    }

    return typeof props.fallback === 'function' ? props.fallback() : null;
  },
  'Show',
  'Slot',
  false
) as ShowNode;

export type SlotProps = {
  for: () => ReactNode;
  children?: ReactNode | (() => ReactNode);
};

/**
 * Renders content based on a slot function.
 *
 * @param props.for - The slot function to render.
 * @param props.children - Optional content to render if no slot function is provided.
 * @returns The rendered content from the slot function or children.
 */
export const Slot = snippet<SlotProps>(
  (props) => {
    return props.for?.() ?? (typeof props.children === 'function' ? props.children() : props.children);
  },
  'Fragment',
  'Slot',
  false
);

export type ForProps<T> = {
  each: T[] | (() => T[]) | undefined | null;
  children: (item: T, index: number) => ReactNode;
  fallback?: ReactNode | (() => ReactNode);
};

export type ForNode = <T>(props: ForProps<T>) => ReactNode;

const ForItem = snippet<{ item: unknown; index: number; render: (item: unknown, index: number) => ReactNode }>(
  (props) => props.render(props.item, props.index),
  'ForItem',
  'Slot',
  false
);

const objectKeys = new WeakMap<object, string>();
let nextKeyId = 0;

function getItemKey(item: unknown, index: number) {
  if (typeof item === 'object' && item !== null) {
    let key = objectKeys.get(item);
    if (!key) {
      key = `item-${++nextKeyId}`;
      objectKeys.set(item, key);
    }
    return key;
  }
  return index;
}

/**
 * Conditionally renders a list of items using a map function.
 *
 * @param props.each - The array or accessor to iterate over.
 * @param props.children - The render function for each item.
 * @param props.fallback - Optional content to render when the array is empty.
 * @returns The rendered list or fallback.
 */
export const For = snippet<ForProps<unknown>>(
  (props) => {
    const check = typeof props.each === 'function' ? props.each : () => props.each;
    const items = check() as unknown[] | undefined | null;

    if (items && items.length > 0) {
      return items.map((item, index) => {
        return <ForItem key={getItemKey(item, index)} item={item} index={index} render={props.children} />;
      });
    }

    return typeof props.fallback === 'function' ? props.fallback() : props.fallback || null;
  },
  'For',
  'Slot',
  false
) as ForNode;
