// apps/react/src/components/todo/TodoItem.tsx
import { type FC, memo, useRef } from 'react';
import { flashNode, todoStats, useUpdateStat } from '../stats/stats.js';
import { type ITodoItem, type ITodoList } from '../../lib/todo.js';
import { Button } from '../Button.js';
import { Trash2 } from 'lucide-react';
import { observed } from '@anchor/react';

export const TodoItem: FC<{ todos: ITodoList; todo: ITodoItem }> = observed(
  memo(({ todos, todo }) => {
    const ref = useRef(null);

    flashNode(ref.current);
    useUpdateStat(() => {
      todoStats.item.value++;
    });

    const handleRemove = () => {
      todos.splice(todos.indexOf(todo), 1);
    };

    return (
      <>
        <li ref={ref} key={todo.id} className="flex items-center gap-2">
          <div className="flex items-center flex-1 gap-3 bg-slate-800/70 p-2 rounded-md">
            <input
              type="checkbox"
              checked={todo.completed}
              onChange={() => (todo.completed = !todo.completed)}
              className="w-5 h-5 rounded bg-slate-700 border-slate-600 text-brand-purple focus:ring-brand-purple"
            />
            <span className={`${todo.completed ? 'flex-1 line-through text-slate-500' : 'flex-1'}`}>{todo.text}</span>
          </div>
          <Button onClick={() => handleRemove()} className="p-2 text-red-400 hover:bg-red-900/50">
            <Trash2 size={14} />
          </Button>
        </li>
      </>
    );
  }),
  'TodoItem'
);

// apps/vue/src/components/todo/TodoItem.vue
<script setup lang="ts">
  import type { ITodo, ITodoList } from './types.js';
  import { propsRef } from '@anchor/vue';
  import { ref } from 'vue';
  import { flashNode } from '../../lib/node.js';

  const props = defineProps<{ todos: ITodoList; todo: ITodo }>();
  const { todos } = props;
  const { todo } = propsRef(props);

  const handleRemove = () => {
    todos.splice(todos.indexOf(todo.value), 1);
  };

  const itemRef = ref(null);
  flashNode(itemRef);
</script>

<template>
  <li ref="itemRef" class="todo-item p-4 hover:bg-gray-100 dark:hover:bg-slate-700 transition duration-150 flex items-center">
    <input type="checkbox" v-model="todo.completed" class="h-5 w-5 text-blue-600 rounded focus:ring-blue-500" />
    <span :class="{ 'line-through text-gray-400': todo.completed }" class="flex-1 ml-3 text-gray-700 dark:text-slate-200">
      {{ todo.text }}
    </span>
    <button
      @click="handleRemove"
      class="ml-2 text-red-500 hover:text-red-700 dark:text-red-400 dark:hover:text-red-300 font-bold py-1 px-2 rounded transition duration-200">
      X
    </button>
  </li>
</template>
