// apps/svelte/src/lib/components/todo/TodoList.svelte
<script lang="ts">
	import TodoStats from './TodoStats.svelte';
	import { flashNode } from '../../node.svelte.js';
	import { anchorRef, observedRef } from '@anchor/svelte';
	import TodoItem from '$lib/components/todo/TodoItem.svelte';
	import type { TodoRecList } from '../../todos.js';

	const { todos }: { todos: TodoRecList } = $props();
	const items = observedRef(() => todos.filter((todo) => !todo.deleted_at));

	let listRef = anchorRef<HTMLElement | null>(null);
	flashNode(listRef);
</script>

<ul
	bind:this={$listRef}
	class="todo-list divide-y divide-gray-200 rounded-lg bg-gray-50 dark:divide-slate-600 dark:bg-slate-700"
>
	{#each $items as todo (todo.id)}
		<TodoItem {todo} />
	{:else}
		<li class="p-4 text-center text-gray-500 dark:text-slate-400">
			No tasks yet. Add a new task to get started!
		</li>
	{/each}
</ul>

<TodoStats {todos} />

// apps/vue/src/components/todo/TodoList.vue
<script setup lang="ts">
  import { propsRef } from '@anchor/vue';
  import TodoItem from './TodoItem.vue';
  import TodoStats from './TodoStats.vue';
  import { ref } from 'vue';
  import { flashNode } from '../../lib/node.js';
  import type { TodoRecList } from '../../lib/todos.js';

  const props = defineProps<{ todos: TodoRecList }>();
  const { todos } = propsRef(props);

  const listRef = ref(null);
  flashNode(listRef);
</script>

<template>
  <ul
    ref="listRef"
    class="todo-list bg-gray-50 dark:bg-slate-700 rounded-lg divide-y divide-gray-200 dark:divide-slate-600">
    <template v-for="todo in todos" :key="todo.id">
      <TodoItem v-if="!todo.deleted_at" :todo :todos />
    </template>
    <li v-if="todos.length === 0" class="p-4 text-center text-gray-500 dark:text-slate-400">
      No tasks yet. Add a new task to get started!
    </li>
  </ul>
  <TodoStats :todos />
</template>
