// apps/svelte/src/lib/components/todo/TodoItem.svelte
<script lang="ts">
	import { type TodoRec, todoTable } from '../../todos.js';
	import { anchorRef, propsRef } from '@anchor/svelte';
	import Trash from '../icons/Trash.svelte';
	import { flashNode } from '../../node.svelte.js';

	const _props: { todo: TodoRec } = $props();
	const { todo } = propsRef(_props);

	const handleRemove = (id: string) => {
		todoTable.remove(id);
	};

	let itemRef = anchorRef<HTMLElement | null>(null);
	flashNode(itemRef);
</script>

<li
	bind:this={$itemRef}
	class="todo-item flex items-center p-4 transition duration-150 hover:bg-gray-100 dark:hover:bg-slate-900"
>
	<input
		type="checkbox"
		bind:checked={$todo.completed}
		class="h-5 w-5 rounded text-blue-600 focus:ring-blue-500"
	/>
	<span
		class:line-through={$todo.completed}
		class:text-gray-400={$todo.completed}
		class="ml-3 flex-1 text-gray-700 dark:text-slate-200"
	>
		{$todo.text}
	</span>
	<button
		onclick={() => handleRemove($todo.id)}
		class="ml-2 rounded px-2 py-1 text-red-600 opacity-80 transition duration-200 hover:opacity-100 dark:text-slate-300"
	>
		<Trash class="w-6" />
	</button>
</li>

// apps/vue/src/components/todo/TodoItem.vue
<script setup lang="ts">
  import { propsRef } from '@anchor/vue';
  import { ref } from 'vue';
  import { flashNode } from '../../lib/node.js';
  import { type TodoRec, type TodoRecList, todoTable } from '../../lib/todos.js';
  import Trash from '../icons/Trash.vue';

  const props = defineProps<{ todos: TodoRecList; todo: TodoRec }>();
  const { todo } = propsRef(props);

  const handleRemove = (id: string) => {
    todoTable.remove(id);
  };

  const itemRef = ref(null);
  flashNode(itemRef);
</script>

<template>
  <li
    ref="itemRef"
    class="todo-item p-4 hover:bg-gray-100 dark:hover:bg-slate-900 transition duration-150 flex items-center">
    <input type="checkbox" v-model="todo.completed" class="h-5 w-5 text-blue-600 rounded focus:ring-blue-500" />
    <span
      :class="{ 'line-through text-gray-400': todo.completed }"
      class="flex-1 ml-3 text-gray-700 dark:text-slate-200">
      {{ todo.text }}
    </span>
    <button
      @click="handleRemove(todo.id)"
      class="ml-2 text-red-600 dark:text-slate-300 py-1 px-2 rounded transition duration-200 opacity-80 hover:opacity-100">
      <Trash class="w-6" />
    </button>
  </li>
</template>
