// templates/react-ssr/src/pages/auth/signup/page.tsx
import { form, mutable } from '@anchorlib/core';
import { $bind, $use, Meta, page, setup, snippet, Title } from '@anchorlib/react';
import type { FormEventHandler } from 'react';
import { z } from 'zod';
import { CheckboxField } from '../../../components/CheckboxField.js';
import { InputField } from '../../../components/InputField.js';
import { signUpRoute } from './route.js';

const schema = z
  .object({
    email: z.string().email(),
    password: z.string().min(8),
    confirmPassword: z.string().min(8),
  })
  .refine((d) => d.password === d.confirmPassword, {
    message: 'Passwords do not match',
    path: ['confirmPassword'],
  });

const SignUpForm = setup(() => {
  const [credentials, errors] = form(schema, { email: '', password: '', confirmPassword: '' });
  const auth = mutable({ submitted: false, remember: false, accepted: false });

  const signup: FormEventHandler<HTMLFormElement> = (e) => {
    e.preventDefault();
    if (!auth.accepted) return;
    if (errors.email || errors.password || errors.confirmPassword) return;
    auth.submitted = true;
  };

  const SubmitButton = snippet(
    () => (
      <button type="submit" className="btn-counter" disabled={!auth.accepted}>
        Sign Up
      </button>
    ),
    'SubmitButton'
  );

  const SubmitMessage = snippet(
    () => (auth.submitted ? <p className="submit-message">Welcome, {credentials.email}!</p> : null),
    'SubmitMessage'
  );

  return (
    <form className="auth-form" onSubmit={signup}>
      <InputField
        id="email"
        type="email"
        label="Email"
        value={$bind(credentials, 'email')}
        error={$use(errors, 'email')}
      />
      <InputField
        id="password"
        type="password"
        label="Password"
        value={$bind(credentials, 'password')}
        error={$use(errors, 'password')}
      />
      <InputField
        id="confirm-password"
        type="password"
        label="Confirm Password"
        value={$bind(credentials, 'confirmPassword')}
        error={$use(errors, 'confirmPassword')}
      />
      <CheckboxField id="remember" label="Remember me" checked={$bind(auth, 'remember')} />
      <CheckboxField id="accepted" label="I accept the terms and conditions" checked={$bind(auth, 'accepted')} />
      <SubmitButton />
      <SubmitMessage />
    </form>
  );
}, 'SignUpForm');

export const SignUpPage = page(signUpRoute).render(() => (
  <>
    <Title>Sign Up — AIR Stack</Title>
    <Meta name="description" content="Create your account." />
    <SignUpForm />
  </>
));
export default SignUpPage;

// templates/air-solid/src/pages/auth/signup/page.tsx
import { $bind, derived, form, Meta, mutable, page, Title } from '@anchorlib/solid';
import type { JSX } from 'solid-js';
import { z } from 'zod';
import { CheckboxField } from '../../../components/CheckboxField.js';
import { InputField } from '../../../components/InputField.js';
import { signUp } from './function.js';
import { signUpRoute } from './route.js';

const schema = z
  .object({
    email: z.string().email(),
    password: z.string().min(8),
    confirmPassword: z.string().min(8),
  })
  .refine((d) => d.password === d.confirmPassword, {
    message: 'Passwords do not match',
    path: ['confirmPassword'],
  });

function SignUpForm() {
  const [credentials, errors] = form(schema, { email: '', password: '', confirmPassword: '' });
  const auth = mutable({ submitted: false, remember: false, accepted: false });

  const signup: JSX.EventHandlerUnion<HTMLFormElement, SubmitEvent> = async (e) => {
    e.preventDefault();
    if (!auth.accepted) return;
    if (errors.email || errors.password || errors.confirmPassword) return;
    try {
      await signUp({ email: credentials.email, password: credentials.password });
      auth.submitted = true;
    } catch (err: any) {
      console.error(err);
    }
  };

  const isAccepted = derived(() => auth.accepted);
  const submitMessage = derived(() => (auth.submitted ? `Welcome, ${credentials.email}!` : ''));

  return (
    <form class="auth-form" onSubmit={signup}>
      <InputField id="email" type="email" label="Email" value={$bind(credentials, 'email')} error={errors.email} />
      <InputField
        id="password"
        type="password"
        label="Password"
        value={$bind(credentials, 'password')}
        error={errors.password}
      />
      <InputField
        id="confirm-password"
        type="password"
        label="Confirm Password"
        value={$bind(credentials, 'confirmPassword')}
        error={errors.confirmPassword}
      />
      <CheckboxField id="remember" label="Remember me" checked={$bind(auth, 'remember')} />
      <CheckboxField id="accepted" label="I accept the terms and conditions" checked={$bind(auth, 'accepted')} />
      <button type="submit" class="btn-counter" disabled={!isAccepted.value}>
        Sign Up
      </button>
      {submitMessage.value ? <p class="submit-message">{submitMessage.value}</p> : null}
    </form>
  );
}

export const SignUpPage = page(signUpRoute).render(() => (
  <>
    <Title>Sign Up — AIR Stack</Title>
    <Meta name="description" content="Create your account." />
    <SignUpForm />
  </>
));
export default SignUpPage;
