// packages/react/src/switch.ts
import { getContext, setContext } from '@anchorlib/core';
import type { ReactNode } from 'react';
import { render, setup, snippet } from './hoc.js';

export type SlotProps<K> = {
  for: K;
  children?: ReactNode | (() => ReactNode);
};

export type SlotNode<K> = (props: SlotProps<K>) => ReactNode;

export type SwitchProps<T> = {
  for: T;
  children?: ReactNode;
};

export type SwitchNode<T, K> = ((props: SwitchProps<T>) => ReactNode) & {
  displayName: string;
  Slot: SlotNode<K>;
};

/**
 * Creates a Slot component that conditionally renders its children based on a context value.
 *
 * @param ctx - The context key to retrieve the state from.
 * @param key - The property key within the state to compare against.
 * @param displayName - Optional display name for the component.
 * @returns A Slot component.
 */
export function createSlot<K>(ctx: string | symbol, key: string | symbol, displayName = 'Anonymous') {
  return snippet<SlotProps<string>>(
    (props) => {
      const state = getContext(ctx) as Record<string, unknown>;
      if (!state) return '<>[Slot Error: Slot rendered outside of Switch]</>';
      const children = typeof props.children === 'function' ? props.children() : props.children;
      return state[key as string] === props.for ? children : null;
    },
    displayName,
    'Slot',
    false
  ) as SlotNode<K>;
}

/**
 * Creates a Switch component and an associated Slot component for conditional rendering.
 *
 * @param ctx - The context key to store the switch state.
 * @param key - The property key within the state that Slots will check.
 * @param displayName - Optional display name for the Switch component.
 * @param scopeName - Optional scope name for the display name (defaults to 'Switch').
 * @returns A Switch component with a static Slot property.
 */
export function createSwitch<T, K>(
  ctx: string | symbol,
  key: string | symbol,
  displayName = 'Anonymous',
  scopeName = 'Switch'
) {
  const Switch = setup((props) => {
    setContext(ctx, (props as never as SwitchProps<T>).for);
    return render(() => (props as never as SwitchProps<T>).children);
  }, displayName) as SwitchNode<T, K>;

  Switch.displayName = `${scopeName}(${displayName})`;
  Switch.Slot = createSlot<K>(ctx, key, displayName);

  return Switch as SwitchNode<T, K>;
}

export type ShowProps<T> = {
  when: T | (() => T);
  children: ReactNode | ((value: T) => ReactNode);
  fallback?: () => ReactNode;
};

export type ShowNode = <T>(props: ShowProps<T>) => ReactNode;

/**
 * Conditionally renders children based on a truthy condition.
 *
 * @param props.when - The condition to evaluate.
 * @param props.children - The content to render when the condition is truthy.
 * @param props.fallback - Optional content to render when the condition is falsy.
 * @returns The rendered content or null.
 */
export const Show = snippet<ShowProps<boolean>>(
  (props) => {
    const check = typeof props.when === 'function' ? props.when : () => props.when;
    const value = check() as boolean;

    if (value) {
      return typeof props.children === 'function' ? props.children(value) : props.children;
    }

    return typeof props.fallback === 'function' ? props.fallback() : null;
  },
  'Show',
  'Slot',
  false
) as ShowNode;

// packages/solid/src/switch.ts
import { createMemo, type JSX } from 'solid-js';
import { render } from './hoc.tsx';

export type ShowProps<T> = {
  when: T;
  children: JSX.Element | ((value: NonNullable<T>) => JSX.Element);
  fallback?: JSX.Element;
};

/**
 * Conditionally renders children based on a truthy condition.
 * Passes the unwrapped truthy value to the children render prop.
 *
 * @param props.when - The condition to evaluate.
 * @param props.children - The content to render when the condition is truthy.
 * @param props.fallback - Optional content to render when the condition is falsy.
 * @returns The rendered content or null.
 */
export function Show<T>(props: ShowProps<T>): JSX.Element {
  const condition = createMemo(() => props.when);
  return createMemo(() => {
    const value = condition();
    if (value) {
      const child = props.children;
      return typeof child === 'function' ? child(value as NonNullable<T>) : child;
    }
    return props.fallback;
  }) as unknown as JSX.Element;
}

export type SnippetProps<T> = {
  data?: T;
  children: (data: T) => JSX.Element;
};

/**
 * A snippet renderer component that allows for dynamic data rendering and destructure access
 * without losing the fine-grained reactivity.
 *
 * Each property of the data object is proxied to a function that returns the corresponding value.
 *
 * @param props.data - The data to render.
 * @param props.children - The render function that takes the data and returns a JSX element.
 * @returns A JSX element.
 */
export function Snippet<T>(props: SnippetProps<T>): JSX.Element {
  const data = createMemo(() => props.data);
  return render(({ children }) => {
    if (typeof children !== 'function') {
      return `[Snippet Error: Snippet must pass function as the children]`;
    }
    return children(data() as T);
  }, props) as unknown as JSX.Element;
}

export type SlotProps = {
  for: JSX.Element;
  children?: JSX.Element | (() => JSX.Element);
};

/**
 * Renders content based on a slot function or expression.
 *
 * @param props.for - The slot content or function to render.
 * @param props.children - Optional content to render if no slot content is provided.
 * @returns The rendered content from the slot function or children.
 */
export function Slot(props: SlotProps): JSX.Element {
  const content = createMemo(() => props.for);
  return createMemo(() => {
    const value = content();
    if (value !== undefined && value !== null) {
      return value;
    }
    const fallback = props.children;
    return typeof fallback === 'function' ? (fallback as () => JSX.Element)() : fallback;
  }) as unknown as JSX.Element;
}
