// ui-kits/solid-form/src/inputs/DatePicker.tsx
import type { Bindable } from '@airlib/solid';
import type { JSX } from 'solid-js';
import { createInput } from './createInput.js';

export interface DatePickerProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<Date>;
}
export const DatePicker = createInput<DatePickerProps>('date');

// ui/react-form/src/inputs/DatePicker.tsx
import type { Bindable } from '@airlib/react';
import type { InputHTMLAttributes } from 'react';
import { createInput } from './createInput.js';

export interface DatePickerProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'value'> {
  value?: Bindable<Date>;
  errorClass?: string;
}
export const DatePicker = createInput<DatePickerProps>('date');
