// ui-kits/solid-form/src/inputs/EmailInput.tsx
import type { Bindable } from '@airlib/solid';
import type { JSX } from 'solid-js';
import { createInput } from './createInput.js';

export interface EmailInputProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<string>;
}
export const EmailInput = createInput<EmailInputProps>('email');

// ui/react-form/src/inputs/EmailInput.tsx
import type { Bindable } from '@airlib/react';
import type { InputHTMLAttributes } from 'react';
import { createInput } from './createInput.js';

export interface EmailInputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'value'> {
  errorClass?: string;
  value?: Bindable<string>;
}
export const EmailInput = createInput<EmailInputProps>('email');
